### PR TITLE
Add containers support

### PR DESCRIPTION
**Pull request by xmnlab**
This PR is a result of a pair programming session with @EverVino 

most of the content here is an adaptation from github.com/thegraphnetwork/epigraphhub

### CODE REVIEW

**Comment by EverVino** [comment]
I was trying to deploy the service locally.
I have questions:
I see in the gitthub workflows file that there are command to activate the mamba environment. To deploy locally I cannot find the command which activates the environment inside the docker image.  Is that command needed? Or is on another file.

**Comment by EverVino** [comment]
in the workflow from the dockerfile 
```
&& chmod -R a+rwx /opt/conda /opt/services \
```
Seems to run in an infinite loop, is that normal, or I'm missing something

**Comment by xmnlab** [comment]
> Seems to run in an infinite loop, is that normal, or I'm missing something

@EverVino it is just very slow

btw, the CI is green .. do you remember if it is ready to go? or is there anything else missing?

**Comment by xmnlab** [comment]
> I see in the gitthub workflows file that there are command to activate the mamba environment. To deploy locally I cannot find the command which activates the environment inside the docker image. Is that command needed? Or is on another file.

inside the container the activation happens via the entrypoint: https://github.com/thegraphnetwork/python-shiny-app-template/pull/2/files#diff-6de51888977847b40c4fbacdf752ecce5fbea741a99bbb1d25020c25219a7483

**Comment by EverVino** [comment]
> > Seems to run in an infinite loop, is that normal, or I'm missing something
> 
> @EverVino it is just very slow
> 
> btw, the CI is green .. do you remember if it is ready to go? or is there anything else missing?

Thanks for let me know Yes it was very slow. I realized about the entrypoint as well.
There was a problem with the port. Locally the shiny app does not showing nothing in the shared port

**Comment by xmnlab** [comment]
got it. 
so is it ok if we merge this PR? or do you want to push anything else here?

**Comment by EverVino** [comment]
> got it. so is it ok if we merge this PR? or do you want to push anything else here?

It's Ok for merge (just the thing about the port maybe it's because my config files). No pushes for now.

**Comment by xmnlab** [comment]
> It's Ok for merge (just the thing about the port maybe it's because my config files). No pushes for now.

maybe there is still something wrong, so feel free to open a new PR to resolve this if it is necessary :)
thank you so much

**Pull request merged**
